### ISSUE TITLE
BUG: Stash

### ISSUE THREAD

**Issue by joao-blip** [opentibiabr/otservbr-global#2441]
`2021-02-21 08:07:15 -  Thread 1 (Thread 0x7ffff7fd3780 (LWP 17607)):
2021-02-21 08:07:15 -  #0  0x00005555557530e4 in Player::postRemoveNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #1  0x00005555555d3a77 in Game::internalRemoveItem(Item*, int, bool, unsigned int) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #2  0x0000555555746649 in Player::removeItemClientId(unsigned short, unsigned int) const ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #3  0x00005555557552f7 in Player::stashContainer(std::map<unsigned short, std::pair<bool, unsigned int>, std::less<unsigned short>, std::allocator<std::pair<unsigned short const, std::pair<bool, unsigned int> > > >) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #4  0x0000555555757bd1 in Player::stowContainer(Item*, unsigned int) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #5  0x0000555555777f2e in ProtocolGame::parseStashWithdraw(NetworkMessage&) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #6  0x000055555577cb24 in ProtocolGame::parsePacket(NetworkMessage&) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #7  0x0000555555822107 in Connection::parsePacket(boost::system::error_code const&) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #8  0x0000555555823cce in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >::operator()(boost::system::error_code const&, unsigned long, int) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #9  0x0000555555824123 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #10 0x00005555557a53f1 in ServiceManager::run() ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  #11 0x000055555558cd2b in main ()
2021-02-21 08:07:15 -  No symbol table info available.
2021-02-21 08:07:15 -  Saving server...`

**Comment by henriquesameshima** [comment]
You know how can I reproduce this?

**Comment by dudantas** [comment]
You are using branch develop or open pull request?

**Comment by Bipbop69** [comment]
> You know how can I reproduce this?

haven't figured it out yet .. 

> You are using branch develop or open pull request?

the current

**Comment by dudantas** [comment]
And how did you reproduce the bug? We need to understand in order to find the solution.

**Comment by marcosvf132** [comment]
I have downloaded a fresh repository right now and cant reproduce the crash. Im waiting your feedback so we can find and fix this issue.

**Comment by Bipbop69** [comment]
> And how did you reproduce the bug? We need to understand in order to find the solution.

I said I didn't find how to reproduce the bug.
I'm just looking at the error log
