### ISSUE TITLE
[Bug]: Monster "Many Face" Crash server

### ISSUE THREAD

**Issue by Methemia** [opentibiabr/otservbr-global#2747]
### What happened?

when a player goes to dark thais and finds the many face the server goes down

### How to Reproduce?

when the monster attacks you the server crashes, I suspect that the error is in one of its spells

### Attach any relevant file

2021-09-17 02:01:49 -  Thread 2 "tfs" received signal SIGSEGV, Segmentation fault.
2021-09-17 02:01:49 -  [Switching to Thread 0x7ffff79d8700 (LWP 447759)]
2021-09-17 02:01:49 -  0x0000555555673416 in LuaScriptInterface::getLuaState() const ()
2021-09-17 02:01:49 -  
2021-09-17 02:01:49 -  Thread 4 (Thread 0x7ffff69c2700 (LWP 447761)):
2021-09-17 02:01:49 -  #0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556357a48 <g_databaseTasks+136>) at ../sysdeps/nptl/futex-internal.h:183
2021-09-17 02:01:49 -          __ret = -512
2021-09-17 02:01:49 -          oldtype = 0
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          oldtype = <optimized out>
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          __ret = <optimized out>
2021-09-17 02:01:49 -          resultvar = <optimized out>
2021-09-17 02:01:49 -          __arg4 = <optimized out>
2021-09-17 02:01:49 -          __arg3 = <optimized out>
2021-09-17 02:01:49 -          __arg2 = <optimized out>
2021-09-17 02:01:49 -          __arg1 = <optimized out>
2021-09-17 02:01:49 -          _a4 = <optimized out>
2021-09-17 02:01:49 -          _a3 = <optimized out>
2021-09-17 02:01:49 -          _a2 = <optimized out>
2021-09-17 02:01:49 -          _a1 = <optimized out>
2021-09-17 02:01:49 -  #1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555563579f8 <g_databaseTasks+56>, cond=0x555556357a20 <g_databaseTasks+96>) at pthread_cond_wait.c:508
2021-09-17 02:01:49 -          spin = 0
2021-09-17 02:01:49 -          buffer = {__routine = 0x7ffff7fae050 <__condvar_cleanup_waiting>, __arg = 0x7ffff69c1cd0, __canceltype = 0, __prev = 0x0}
2021-09-17 02:01:49 -          cbuffer = {wseq = 84, cond = 0x555556357a20 <g_databaseTasks+96>, mutex = 0x5555563579f8 <g_databaseTasks+56>, private = 0}
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          g = 0
2021-09-17 02:01:49 -          flags = <optimized out>
2021-09-17 02:01:49 -          g1_start = <optimized out>
2021-09-17 02:01:49 -          signals = <optimized out>
2021-09-17 02:01:49 -          result = 0
2021-09-17 02:01:49 -          wseq = 84
2021-09-17 02:01:49 -          seq = 42
2021-09-17 02:01:49 -          private = <optimized out>
2021-09-17 02:01:49 -          maxspin = <optimized out>
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          result = <optimized out>
2021-09-17 02:01:49 -          wseq = <optimized out>
2021-09-17 02:01:49 -          g = <optimized out>
2021-09-17 02:01:49 -          seq = <optimized out>
2021-09-17 02:01:49 -          flags = <optimized out>
2021-09-17 02:01:49 -          private = <optimized out>
2021-09-17 02:01:49 -          signals = <optimized out>
2021-09-17 02:01:49 -          g1_start = <optimized out>
2021-09-17 02:01:49 -          spin = <optimized out>
2021-09-17 02:01:49 -          buffer = <optimized out>
2021-09-17 02:01:49 -          cbuffer = <optimized out>
2021-09-17 02:01:49 -          s = <optimized out>
2021-09-17 02:01:49 -  #2  __pthread_cond_wait (cond=0x555556357a20 <g_databaseTasks+96>, mutex=0x5555563579f8 <g_databaseTasks+56>) at pthread_cond_wait.c:638
2021-09-17 02:01:49 -  No locals.
2021-09-17 02:01:49 -  #3  0x00007ffff7d37e30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #4  0x000055555577dcfe in DatabaseTasks::threadMain() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #5  0x00005555557809c0 in void std::__invoke_impl<void, void (DatabaseTasks::*)(), DatabaseTasks*>(std::__invoke_memfun_deref, void (DatabaseTasks::*&&)(), DatabaseTasks*&&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #6  0x0000555555780903 in std::__invoke_result<void (DatabaseTasks::*)(), DatabaseTasks*>::type std::__invoke<void (DatabaseTasks::*)(), DatabaseTasks*>(void (DatabaseTasks::*&&)(), DatabaseTasks*&&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #7  0x0000555555780873 in void std::thread::_Invoker<std::tuple<void (DatabaseTasks::*)(), DatabaseTasks*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #8  0x000055555578082e in std::thread::_Invoker<std::tuple<void (DatabaseTasks::*)(), DatabaseTasks*> >::operator()() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #9  0x0000555555780814 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (DatabaseTasks::*)(), DatabaseTasks*> > >::_M_run() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #10 0x00007ffff7d3dde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #11 0x00007ffff7fa7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2021-09-17 02:01:49 -          ret = <optimized out>
2021-09-17 02:01:49 -          pd = <optimized out>
2021-09-17 02:01:49 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737330816768, 8177034980633236144, 140737347678990, 140737347678991, 140737347678992, 140737330814848, -8177053933289188688, -8177052542544096592}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-09-17 02:01:49 -          not_first_call = 0
2021-09-17 02:01:49 -  #12 0x00007ffff7b7c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-09-17 02:01:49 -  No locals.
2021-09-17 02:01:49 -  
2021-09-17 02:01:49 -  Thread 3 (Thread 0x7ffff71d7700 (LWP 447760)):
2021-09-17 02:01:49 -  #0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7ffff71d6d10, clockid=<optimized out>, expected=0, futex_word=0x555556357b6c <g_scheduler+108>) at ../sysdeps/nptl/futex-internal.h:320
2021-09-17 02:01:49 -          __ret = -516
2021-09-17 02:01:49 -          clockbit = <optimized out>
2021-09-17 02:01:49 -          op = <optimized out>
2021-09-17 02:01:49 -          __ret = <optimized out>
2021-09-17 02:01:49 -          oldtype = 0
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          oldtype = <optimized out>
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          __ret = <optimized out>
2021-09-17 02:01:49 -          clockbit = <optimized out>
2021-09-17 02:01:49 -          op = <optimized out>
2021-09-17 02:01:49 -          __ret = <optimized out>
2021-09-17 02:01:49 -          resultvar = <optimized out>
2021-09-17 02:01:49 -          __arg6 = <optimized out>
2021-09-17 02:01:49 -          __arg5 = <optimized out>
2021-09-17 02:01:49 -          __arg4 = <optimized out>
2021-09-17 02:01:49 -          __arg3 = <optimized out>
2021-09-17 02:01:49 -          __arg2 = <optimized out>
2021-09-17 02:01:49 -          __arg1 = <optimized out>
2021-09-17 02:01:49 -          _a6 = <optimized out>
2021-09-17 02:01:49 -          _a5 = <optimized out>
2021-09-17 02:01:49 -          _a4 = <optimized out>
2021-09-17 02:01:49 -          _a3 = <optimized out>
2021-09-17 02:01:49 -          _a2 = <optimized out>
2021-09-17 02:01:49 -          _a1 = <optimized out>
2021-09-17 02:01:49 -  #1  __pthread_cond_wait_common (abstime=0x7ffff71d6d10, clockid=<optimized out>, mutex=0x555556357b18 <g_scheduler+24>, cond=0x555556357b40 <g_scheduler+64>) at pthread_cond_wait.c:520
2021-09-17 02:01:49 -          spin = 0
2021-09-17 02:01:49 -          buffer = {__routine = 0x7ffff7fae050 <__condvar_cleanup_waiting>, __arg = 0x7ffff71d6c30, __canceltype = -149066624, __prev = 0x0}
2021-09-17 02:01:49 -          cbuffer = {wseq = 120826671, cond = 0x555556357b40 <g_scheduler+64>, mutex = 0x555556357b18 <g_scheduler+24>, private = 0}
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          g = 1
2021-09-17 02:01:49 -          flags = <optimized out>
2021-09-17 02:01:49 -          g1_start = <optimized out>
2021-09-17 02:01:49 -          maxspin = 0
2021-09-17 02:01:49 -          signals = <optimized out>
2021-09-17 02:01:49 -          result = 0
2021-09-17 02:01:49 -          wseq = 120826671
2021-09-17 02:01:49 -          seq = 60413335
2021-09-17 02:01:49 -          private = <optimized out>
2021-09-17 02:01:49 -          maxspin = <optimized out>
2021-09-17 02:01:49 -          err = <optimized out>
2021-09-17 02:01:49 -          result = <optimized out>
2021-09-17 02:01:49 -          wseq = <optimized out>
2021-09-17 02:01:49 -          g = <optimized out>
2021-09-17 02:01:49 -          seq = <optimized out>
2021-09-17 02:01:49 -          flags = <optimized out>
2021-09-17 02:01:49 -          private = <optimized out>
2021-09-17 02:01:49 -          signals = <optimized out>
2021-09-17 02:01:49 -          g1_start = <optimized out>
2021-09-17 02:01:49 -          spin = <optimized out>
2021-09-17 02:01:49 -          buffer = <optimized out>
2021-09-17 02:01:49 -          cbuffer = <optimized out>
2021-09-17 02:01:49 -          s = <optimized out>
2021-09-17 02:01:49 -  #2  __pthread_cond_timedwait (cond=0x555556357b40 <g_scheduler+64>, mutex=0x555556357b18 <g_scheduler+24>, abstime=0x7ffff71d6d10) at pthread_cond_wait.c:656
2021-09-17 02:01:49 -          flags = <optimized out>
2021-09-17 02:01:49 -          clockid = <optimized out>
2021-09-17 02:01:49 -  #3  0x00005555557f9127 in __gthread_cond_timedwait(pthread_cond_t*, pthread_mutex_t*, timespec const*) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #4  0x00005555557fa214 in std::cv_status std::condition_variable::__wait_until_impl<std::chrono::duration<long, std::ratio<1l, 1000000000l> > >(std::unique_lock<std::mutex>&, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #5  0x00005555557f9c9b in std::cv_status std::condition_variable::wait_until<std::chrono::duration<long, std::ratio<1l, 1000000000l> > >(std::unique_lock<std::mutex>&, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #6  0x00005555557f9527 in Scheduler::threadMain() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #7  0x00005555559ee892 in void std::__invoke_impl<void, void (Scheduler::*)(), Scheduler*>(std::__invoke_memfun_deref, void (Scheduler::*&&)(), Scheduler*&&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #8  0x00005555559ee64f in std::__invoke_result<void (Scheduler::*)(), Scheduler*>::type std::__invoke<void (Scheduler::*)(), Scheduler*>(void (Scheduler::*&&)(), Scheduler*&&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #9  0x00005555559ee2ef in void std::thread::_Invoker<std::tuple<void (Scheduler::*)(), Scheduler*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #10 0x00005555559eddea in std::thread::_Invoker<std::tuple<void (Scheduler::*)(), Scheduler*> >::operator()() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #11 0x00005555559ecc62 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Scheduler::*)(), Scheduler*> > >::_M_run() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #12 0x00007ffff7d3dde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #13 0x00007ffff7fa7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2021-09-17 02:01:49 -          ret = <optimized out>
2021-09-17 02:01:49 -          pd = <optimized out>
2021-09-17 02:01:49 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737339291392, 8177034980633236144, 140737488346446, 140737488346447, 140737488346448, 140737339289472, -8177050626701241680, -8177052542544096592}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-09-17 02:01:49 -          not_first_call = 0
2021-09-17 02:01:49 -  #14 0x00007ffff7b7c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-09-17 02:01:49 -  No locals.
2021-09-17 02:01:49 -  
2021-09-17 02:01:49 -  Thread 2 (Thread 0x7ffff79d8700 (LWP 447759)):
2021-09-17 02:01:49 -  #0  0x0000555555673416 in LuaScriptInterface::getLuaState() const ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #1  0x00005555558993d5 in CreatureEvent::executeHealthChange(Creature*, Creature*, CombatDamage&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #2  0x00005555557a4bc2 in Game::combatChangeHealth(Creature*, Creature*, CombatDamage&, bool) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #3  0x00005555556767a6 in Combat::CombatHealthFunc(Creature*, Creature*, CombatParams const&, CombatDamage*) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #4  0x00005555556782bf in Combat::doCombatHealth(Creature*, Creature*, CombatDamage&, CombatParams const&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #5  0x000055555588802a in Weapon::internalUseWeapon(Player*, Item*, Creature*, int) const ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #6  0x00005555558898b0 in WeaponDistance::useWeapon(Player*, Item*, Creature*) const ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #7  0x000055555573cebd in Player::doAttacking(unsigned int) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #8  0x00005555556a1367 in Creature::onAttacking(unsigned int) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #9  0x00005555557a179e in Game::checkCreatureAttack(unsigned int) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #10 0x00005555556afd59 in void std::__invoke_impl<void, void (Game::*&)(unsigned int), Game*&, unsigned int&>(std::__invoke_memfun_deref, void (Game::*&)(unsigned int), Game*&, unsigned int&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #11 0x00005555556af18b in std::__invoke_result<void (Game::*&)(unsigned int), Game*&, unsigned int&>::type std::__invoke<void (Game::*&)(unsigned int), Game*&, unsigned int&>(void (Game::*&)(unsigned int), Game*&, unsigned int&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #12 0x00005555556adb38 in void std::_Bind<void (Game::*(Game*, unsigned int))(unsigned int)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #13 0x00005555556aba5b in void std::_Bind<void (Game::*(Game*, unsigned int))(unsigned int)>::operator()<, void>() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #14 0x00005555556a9edb in std::_Function_handler<void (), std::_Bind<void (Game::*(Game*, unsigned int))(unsigned int)> >::_M_invoke(std::_Any_data const&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #15 0x00005555557fc6fc in std::function<void ()>::operator()() const ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #16 0x00005555557fc21e in Task::operator()() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #17 0x00005555557fc457 in Dispatcher::threadMain() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #18 0x00005555559ee94a in void std::__invoke_impl<void, void (Dispatcher::*)(), Dispatcher*>(std::__invoke_memfun_deref, void (Dispatcher::*&&)(), Dispatcher*&&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #19 0x00005555559ee6df in std::__invoke_result<void (Dispatcher::*)(), Dispatcher*>::type std::__invoke<void (Dispatcher::*)(), Dispatcher*>(void (Dispatcher::*&&)(), Dispatcher*&&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #20 0x00005555559ee339 in void std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #21 0x00005555559ede04 in std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::operator()() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #22 0x00005555559ecc84 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> > >::_M_run() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #23 0x00007ffff7d3dde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #24 0x00007ffff7fa7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2021-09-17 02:01:49 -          ret = <optimized out>
2021-09-17 02:01:49 -          pd = <optimized out>
2021-09-17 02:01:49 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737347684096, 8177034980633236144, 140737488346446, 140737488346447, 140737488346448, 140737347682176, -8177051726749740368, -8177052542544096592}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-09-17 02:01:49 -          not_first_call = 0
2021-09-17 02:01:49 -  #25 0x00007ffff7b7c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-09-17 02:01:49 -  No locals.
2021-09-17 02:01:49 -  
2021-09-17 02:01:49 -  Thread 1 (Thread 0x7ffff79dbbc0 (LWP 447755)):
2021-09-17 02:01:49 -  #0  0x00007ffff7b7c5ce in epoll_wait (epfd=4, events=0x7fffffffd6c0, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
2021-09-17 02:01:49 -          resultvar = 18446744073709551612
2021-09-17 02:01:49 -          sc_cancel_oldtype = 0
2021-09-17 02:01:49 -          sc_ret = <optimized out>
2021-09-17 02:01:49 -  #1  0x00005555559cd406 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #2  0x00005555559ceb2e in boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #3  0x00005555559ce5b0 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #4  0x0000555555a730f4 in boost::asio::io_context::run() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #5  0x0000555555a742e6 in ServiceManager::run() ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  #6  0x00005555559d3e35 in main ()
2021-09-17 02:01:49 -  No symbol table info available.
2021-09-17 02:01:49 -  > Saved Hirelings
2021-09-17 02:01:49 -  [2021-17-09 02:01:49.628] [info] Saving server... 
2021-09-17 02:01:50 -  [2021-17-09 02:01:50.981] [info] Saved house items in 0.318 seconds 
2021-09-17 02:01:51 -  A debugging session is active.
2021-09-17 02:01:51 -  
2021-09-17 02:01:51 -  	Inferior 1 [process 447755] will be killed.
2021-09-17 02:01:51 -  
2021-09-17 02:01:51 -  Quit anyway? (y or n) [answered Y; input not from terminal]

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
Tfs?

**Comment by hyagosrs** [comment]
i have same crash :(

**Comment by dex-89** [comment]
Engine tfs or otbr?

**Comment by hyagosrs** [comment]
> Engine tfs or otbr?

OTBR

**Comment by Meth28** [comment]
I call it tfs for my autorun script but it is 100% otbr

**Comment by Schiffers** [comment]
Did you get this crash when the server is with no players, and Just startup? 
Clean server etc ... 
NO PLAYERS... 
Recent startup ?

**Comment by Bipbop69** [comment]
I had this error after I removed the boss lulu stopped 
same log

**Comment by hyagosrs** [comment]
> I had this error after I removed the boss lulu stopped
> same log

did you remove urmahlulu completely? explain us

**Comment by Bipbop69** [comment]
I removed all the mechanics and just leave the 'monster'. do the test..
